### ISSUE TITLE
Crash on Enabling the Plugin

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/ShowHandlesEverywhere#4] opened 2017-12-12 15:05 UTC
Version 2.5b (1096)
Just sent a crash report.
I have uninstalled all plugins.

I open this file:
https://www.dropbox.com/s/b8rplrhsoexjg67/New%20Font2.glyphs?dl=0

and I have Fill Preview Off then as soon as I enable this plugin. It crashes.

**Comment by mekkablue** [comment] 2017-12-12 17:35
I can trigger it if _View > Show Nodes_ is off. I’ll have a look.

**Comment by mekkablue** [comment] 2017-12-12 18:01
Try the version I just uploaded. I could not reproduce a crash anymore with other plugins out of the Plugins folder. A few other plug-ins seem to be affected too.

**Comment by schriftgestalt** [comment] 2017-12-12 21:42
Do you know what of the changes made a difference?

**Comment by schriftgestalt** [comment] 2017-12-12 22:54
I have send a pull request

**Comment by mekkablue** [comment] 2017-12-13 13:54
Thanks, I merged it. Seems to work now.

**Closed as completed by mekkablue** 2017-12-13 13:54 UTC
